export const gems = [
    {
        id: '1',
        name: 'Amethyst',
        type: 'amethyst',
        represents: 'purity of spirit',
        gemMonth: 'February',
        hardness: '7',
        metaphysicalProperties: 'relieves stress and anxiety',
    },
    {
        id: '2',
        name: 'Bismuth',
        type: 'bismuth',
        represents: 'vitality and stimulation',
        gemMonth: 'N/A',
        hardness: '2 - 2.5',
        metaphysicalProperties: 'relieves feelings of overwhelm and loneliness',
    },
    {
        id: '3',
        name: 'Citrine',
        type: 'citrine',
        represents: 'positivity and optimism',
        gemMonth: 'November',
        hardness: '7',
        metaphysicalProperties: 'promotes motivation, and encourages self-expression',
    },
    {
        id: '4',
        name: 'Opal',
        type: 'opal',
        represents: 'hope, innocence, and purity ',
        gemMonth: 'October',
        hardness: '5.5 - 6.5',
        metaphysicalProperties: 'amplifies mystical powers and creates a sense of balance',
    },
];